# Quantumult X 模版示例
# 节点、策略组与规则由 Subone 运行时自动注入

[general]
excluded_routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1/32
dns_exclusion_list = *.local, localhost
server_check_url = http://cp.cloudflare.com/generate_204

[dns]
server = 223.5.5.5
server = 119.29.29.29

[policy]

[server_remote]

[server_local]

[filter_remote]

[filter_local]
final=🐟 漏网之鱼
